lib/game_controller_web/router.ex
defmodule GameControllerWeb.Router do
  use GameControllerWeb, :router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GameControllerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :logged_in do
    plug GameControllerWeb.Plugs.LoggedIn
  end

  pipeline :logged_out do
    plug GameControllerWeb.Plugs.LoggedOut
  end

  scope "/", GameControllerWeb do
    pipe_through :browser

    if Mix.env() in [:dev, :test] do
      get "/test-logins", TestLoginsController, :show
      put "/test-logins", TestLoginsController, :reseed
    end

    live "/chat", ChatUnAuthLive, :show

    scope "/" do
      pipe_through :logged_out

      scope "/login" do
        get "/", LoginController, :show
        post "/", LoginController, :create
      end

      scope "/signup" do
        get "/", SignupController, :show
        post "/", SignupController, :create
      end

      scope "/verify-email" do
        get "/", VerifyEmailController, :show
      end
    end

    scope "/" do
      pipe_through :logged_in

      live "/", ServerStatusLive, :show
      delete "/", LoginController, :delete

      import Phoenix.LiveDashboard.Router
      live_dashboard "/dashboard", metrics: GameControllerWeb.Telemetry
    end
  end
end

lib/game_controller_web/views/layout_view.ex
defmodule GameControllerWeb.LayoutView do
  use GameControllerWeb, :view
  alias GameController.Auth
end

lib/game_controller_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>GameController</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/game_controller_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "GameController" %>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>GameController</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <% logged_in = Auth.has_session?(@conn) %>
            <%= if logged_in do %>
              <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
                <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
                <li><%= link "Logout", to: Routes.login_path(@conn, :delete), method: :delete %></li>
              <% end %>
            <% else %>
              <li><%= link "Login", to: Routes.login_path(@conn, :show) %></li>
              <li><%= link "Signup", to: Routes.signup_path(@conn, :show) %></li>
            <% end %>
            <%= if Mix.env() in [:dev, :test] do %>
              <li><%= link "Test logins", to: Routes.test_logins_path(@conn, :show) %></li>
            <% end %>
          </ul>
        </nav>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>